version: 2
jobs:
  build:
    docker:
      - image: ferrarorafael/customer-success-solution:v1

    working_directory: /usr/src/app

    steps:
      - checkout

      - run: echo "Hello world"
      - run: echo "Run tests"
      - run: ruby tests/customer_success_balancing_test.rb
