version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: echo "Hello world"
      - run: echo "Run tests"
      - run: ruby tests/customer_success_balancing_test.rb
